### PR TITLE
adding some details on the node on hover

### PR DESCRIPTION
**Pull request by maxlath**
requested by @belett

### CODE REVIEW

**Comment by belett** [comment]
I'm belett and I approved this idea ;)

**Review by lucaswerkmeister — APPROVED** [review]
So this produces SVG like

```svg
<text dx="12" dy=".35em" xml:lang="de">Satan<title>L1831 - de</title></text>
```

where the `<title>` element comes after the text. [MDN](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/title) says that `<title>` should be the first child element of its parent – but if I understand correctly, the text (here “Satan”) forms a text *node*, but not an *element*, so I think this is okay. (It works as intended in Firefox, at least.)

**Comment by lucaswerkmeister** [comment]
> requested by @belett

by the way, I’m curious [where this happened](http://www.wikidata.org/entity/Q3544030) :P

**Comment by maxlath** [comment]
if the question is where this feature request physically happened, [we are here](https://www.openstreetmap.org/node/5804728693) ([context](http://movilab.org/index.php?title=IndieCamp_Kerbors_2018))

**Comment by lucaswerkmeister** [comment]
Well, I didn’t know that it was a physical location, so I was wondering if there’s some online place where people are requesting features for my tool that I don’t know about :D thanks!

**Pull request merged**
